name: CI/CD Pipeline
run-name: ${{ github.ref }} - ${{ github.ref_name }} by ${{ github.actor }}

permissions:
  contents: read

on:
  pull_request:
    branches: [ "release" ]

jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Git Checkout
        uses: actions/checkout@v3

      - 
        name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: nimeshnela
          password: gmpm1234@Docker
      
      - 
        name: Build and publish with Jib
        run: ./gradlew jib